### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by rishabjasrotia** [OpenSignLabs/OpenSign#152]
I got strange issue on every URL it is throwing 404 error!

![image](https://github.com/OpenSignLabs/OpenSign/assets/33950743/4d85bf41-51fc-43f6-9ced-2bb5e5b7d59d)

**Comment by nxglabs** [comment]
@rishabjasrotia that is because we have modified the start command to serve the contents of build folder which gets created only after running "npn run build". We will have to either change the start command to "npm run start-dev" or add a build command before start. We are working on it. Will update you soon.

**Comment by rishabjasrotia** [comment]
I have raised PR #162 to handle this.
Closing this issue.

**Comment by DoozyDoz** [comment]
I still get this error and followed all instructions in the installation guide
 i tried the digital ocean one first and got stack here
![image](https://github.com/OpenSignLabs/OpenSign/assets/98877504/74d38620-73c6-48bf-8922-2220c25281d5)
next i simply cloned the repo and copied the .env file to the apps/openSign folder as guided, ran npm install and then npm run start and now i get the 404 error
![image](https://github.com/OpenSignLabs/OpenSign/assets/98877504/15e31f1f-4967-4253-a33b-67699efcd3e7)
