### ISSUE TITLE
[Bug]: Installation o Docker Desktop 

### ISSUE THREAD

**Issue by etienneroy11** [OpenSignLabs/OpenSign#339]
### Issue Description

Hi, When I try to install Local Docker instance I receice this error when server container try to install 

Can anyone explain the problem to me or have a solution?

Thank you

### Screenshots of the issue(optional)

![Error log](https://github.com/OpenSignLabs/OpenSign/assets/5375399/6b7e56f8-88c7-42aa-be37-23ab4d2be99f)

### Operating System [e.g. MacOS Sonoma 14.1, Windows 11]

Window 11

### What browsers are you seeing the problem on?

Chrome

### What version of OpenSign™ are you seeing this issue on? [e.g. 1.0.6]

v1.1.1-beta

### What environment are you seeing the problem on?

Dev (localhost or vercel)

### Please check the boxes that apply to this issue report.

- [ ] I have searched the existing issues & discussions to make sure that this is not a duplicate.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

**Comment by lordpayder** [comment]
I get the same problem after building the server and starting it. Tried staging and main branch.

**Comment by rishabjasrotia** [comment]
Yes I validate we have this issue in OpenSignServer Container probably due to new code changes!

**Comment by rishabjasrotia** [comment]
Post Investigation the error is linked to the STMP setup.
We do need to add SMTP details or Mailgun since we are setting the usage of mail mandate.

cc @etienneroy11 @lordpayder 

You can set ```SMTP_ENABLE=true```

It will resolve your issue.

<img width="507" alt="image" src="https://github.com/OpenSignLabs/OpenSign/assets/33950743/32e6fb42-f2de-4c1b-b009-b4ae25488135">

cc @andrew-opensignlabs
