### ISSUE TITLE
[Bug]:  issue after installing XMLHttpRequest failed: "SyntaxError: Unexpected token < in JSON at position 0" when i click up register

### ISSUE THREAD

**Issue by killmasta93** [OpenSignLabs/OpenSign#694]
### Issue Description

Hi currently getting XMLHttpRequest failed: "SyntaxError: Unexpected token < in JSON at position 0" when i click up register after installing 

### Steps to reproduce

from the guide using the step by step when trying to register 
i also checked and another user having the same issue 
https://github.com/OpenSignLabs/OpenSign/issues/559

### Screenshots of the issue(optional)

![image](https://github.com/OpenSignLabs/OpenSign/assets/13953629/50253cd2-5b43-458a-8939-2d017a702d61)

### Operating System [e.g. MacOS Sonoma 14.1, Windows 11]

ubuntu 20 LTS

### What version of OpenSign™ are you seeing this issue on? [e.g. 1.0.6]

1.5.8

### What environment are you seeing the problem on?

Hosted (app.yourdomain.com)

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the existing issues & discussions to make sure that this is not a duplicate.

**Comment by Zathiel** [comment]
Hey @killmasta93 

Are you still facing issues with the last release ?

If not i will mark this issue as solved

**Comment by rubyonrailsstarter** [comment]
I have the same issue when trying to create an account the first time. 

![image](https://github.com/OpenSignLabs/OpenSign/assets/3462499/e160196c-7ad8-495e-9f91-37cccef291a8)

**Comment by Zathiel** [comment]
@rubyonrailsstarter 

Can you provide me docker container logs and version you are running

Regards

**Comment by rubyonrailsstarter** [comment]
opensign-server log: 

> open_sign_server@1.4.0 start
> node index.js
Please provide AWS credintials in env file! Defaulting to local storage.
(node:18) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18) NOTE: The AWS SDK for JavaScript (v2) will enter maintenance mode
on September 8, 2024 and reach end-of-support on September 8, 2025.
Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check blog post at https://a.co/cUPnyil
Please provide valid SMTP credentials
parse-server-example running on port 8080.
An uncaught exception occurred: Invalid endpoint: undefinedStack Trace:
Error: Invalid endpoint: undefined
    at new Endpoint (/usr/src/app/node_modules/aws-sdk/lib/http.js:47:13)
    at file:///usr/src/app/cloud/parsefunction/getSignedUrl.js:8:24
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)

opensign-container: 


> open_sign@0.1.0 start
> serve -s build
 INFO  Accepting connections at http://localhost:3000
 HTTP  6/3/2024 2:48:07 AM 192.168.1.6 GET /
 HTTP  6/3/2024 2:48:07 AM 192.168.1.6 Returned 200 in 22 ms
 HTTP  6/3/2024 2:48:08 AM 192.168.1.6 GET /manifest.json
 HTTP  6/3/2024 2:48:08 AM 192.168.1.6 Returned 200 in 3 ms
 HTTP  6/3/2024 2:48:33 AM 192.168.1.6 POST /app/users
 HTTP  6/3/2024 2:48:33 AM 192.168.1.6 Returned 200 in 2 ms

opensign-mongo:

t={"$date":"2024-06-03T02:47:00.602+00:00"} s=I c=NETWORK id=6788700 ctx=conn15 msg=Received first command on ingress connection since session start or auth handshake attr={"elapsedMillis":1} 
t={"$date":"2024-06-03T02:47:02.099+00:00"} s=I c=NETWORK id=22944 ctx=conn14 msg=Connection ended attr={"remote":"172.20.0.3:60056","uuid":{"uuid":{"$uuid":"41304e42-7b85-4be7-9af9-b32d0e418a31"}},"connectionId":14,"connectionCount":6} 
t={"$date":"2024-06-03T02:47:02.099+00:00"} s=I c=NETWORK id=22944 ctx=conn13 msg=Connection ended attr={"remote":"172.20.0.3:60048","uuid":{"uuid":{"$uuid":"2af92e5c-6551-42b2-aeb6-831e9304417c"}},"connectionId":13,"connectionCount":5} 
t={"$date":"2024-06-03T02:47:02.100+00:00"} s=I c=NETWORK id=22944 ctx=conn12 msg=Connection ended attr={"remote":"172.20.0.3:60044","uuid":{"uuid":{"$uuid":"acf5ecdd-0cb5-4082-84a3-12fd17e419b0"}},"connectionId":12,"connectionCount":4} 
t={"$date":"2024-06-03T02:47:02.100+00:00"} s=I c=NETWORK id=22944 ctx=conn11 msg=Connection ended attr={"remote":"172.20.0.3:60032","uuid":{"uuid":{"$uuid":"98810f53-2049-4979-91f7-a6b51a36cefb"}},"connectionId":11,"connectionCount":3} 
t={"$date":"2024-06-03T02:47:02.100+00:00"} s=I c=NETWORK id=22944 ctx=conn10 msg=Connection ended attr={"remote":"172.20.0.3:60030","uuid":{"uuid":{"$uuid":"f174a622-6ff4-4499-9366-c7e43a840076"}},"connectionId":10,"connectionCount":2} 
t={"$date":"2024-06-03T02:47:02.100+00:00"} s=I c=NETWORK id=22944 ctx=conn9 msg=Connection ended attr={"remote":"172.20.0.3:60022","uuid":{"uuid":{"$uuid":"fb404639-021c-42a6-8a5d-636f1419556d"}},"connectionId":9,"connectionCount":1} 
t={"$date":"2024-06-03T02:47:02.101+00:00"} s=I c=NETWORK id=22944 ctx=conn15 msg=Connection ended attr={"remote":"172.20.0.3:60070","uuid":{"uuid":{"$uuid":"5f114a92-b487-494c-b67a-f3f959695ec3"}},"connectionId":15,"connectionCount":0} 
t={"$date":"2024-06-03T02:47:20.677+00:00"} s=I c=WTCHKPT id=22430 ctx=Checkpointer msg=WiredTiger message attr={"message":{"ts_sec":1717382840,"ts_usec":677569,"thread":"1:0x7fefc8518640","session_name":"WT_SESSION.checkpoint","category":"WT_VERB_CHECKPOINT_PROGRESS","category_id":6,"verbose_level":"DEBUG_1","verbose_level_id":1,"msg":"saving checkpoint snapshot min: 9, snapshot max: 9 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 138"}} 
t={"$date":"2024-06-03T02:48:20.687+00:00"} s=I c=WTCHKPT id=22430 ctx=Checkpointer msg=WiredTiger message attr={"message":{"ts_sec":1717382900,"ts_usec":687736,"thread":"1:0x7fefc8518640","session_name":"WT_SESSION.checkpoint","category":"WT_VERB_CHECKPOINT_PROGRESS","category_id":6,"verbose_level":"DEBUG_1","verbose_level_id":1,"msg":"saving checkpoint snapshot min: 10, snapshot max: 10 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 138"}} 
t={"$date":"2024-06-03T02:49:20.695+00:00"} s=I c=WTCHKPT id=22430 ctx=Checkpointer msg=WiredTiger message attr={"message":{"ts_sec":1717382960,"ts_usec":695547,"thread":"1:0x7fefc8518640","session_name":"WT_SESSION.checkpoint","category":"WT_VERB_CHECKPOINT_PROGRESS","category_id":6,"verbose_level":"DEBUG_1","verbose_level_id":1,"msg":"saving checkpoint snapshot min: 11, snapshot max: 11 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 138"}}

**Comment by rubyonrailsstarter** [comment]
opensignsever-container docker log: the container exits with the following error. I'm using mailgun API key to send email.

> open_sign_server@1.4.0 start
> node index.js
Please provide AWS credintials in env file! Defaulting to local storage.
(node:19) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19) NOTE: The AWS SDK for JavaScript (v2) will enter maintenance mode
on September 8, 2024 and reach end-of-support on September 8, 2025.
Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check blog post at https://a.co/cUPnyil

Please provide valid SMTP credentials
parse-server-example running on port 8080.

An uncaught exception occurred: Invalid endpoint: undefinedStack Trace:
Error: Invalid endpoint: undefined
    at new Endpoint (/usr/src/app/node_modules/aws-sdk/lib/http.js:47:13)
    at file:///usr/src/app/cloud/parsefunction/getSignedUrl.js:8:24
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)

**Comment by nxglabs** [comment]
I hope this issue is resolved, if not please join our discord server to discuss this.
