### ISSUE TITLE
Change page titles

### ISSUE THREAD

**Issue by andrew-opensignlabs** [OpenSignLabs/OpenSign#85]
Change page titles for all pages from -
"contracts - Page Title" to **Page Title - OpenSign™**

For example -
The title of Dashboard page is "contracts - Dashboard" but it should be **Dashboard - OpenSign™**

**Comment by arianxq** [comment]
can I work on this issue ?

**Comment by arianxq** [comment]
@andrew-opensignlabs 
Does it mean like this? Change <Title title="Dashboard" /> to <Title title="Dashboard - OpenSign™" />
![image](https://github.com/OpenSignLabs/OpenSign/assets/122199576/2442a9b3-43b2-4bb8-a26a-7941a9566eeb)

**Comment by satyadev2** [comment]
hello @nxglabs @andrew-opensignlabs , actually i have fixed this issue on landing page but i am getting some problem while signing up , i need to change rest of pages so i need to login .
![image](https://github.com/OpenSignLabs/OpenSign/assets/91907695/dae40d26-7113-4fe6-8cf1-29cb32392290)


Error while Creating Account, is it because of database?
![image](https://github.com/OpenSignLabs/OpenSign/assets/91907695/2e594884-317b-469b-bade-3a03cc41d6a1)

**Comment by nxglabs** [comment]
Follow the steps mentioned in INSTALLATION.md properly to get it running properly on localhost.
