### ISSUE TITLE
[Possible Bug]: Hardcoded env values in runmigrate

### ISSUE THREAD

**Issue by wafflesrg00d** [OpenSignLabs/OpenSign#917]
https://github.com/OpenSignLabs/OpenSign/blob/e50f062a911f04e3f8d7d9161ae200ca1fd8708d/apps/OpenSignServer/runmigrate.js#L6

Why is Line 6 commented out vs. Line 5? I ran into the below error when running the project locally, this hardcoded line was the culprit.

`OpenSignServer-container  | ParseError: XMLHttpRequest failed: "Unable to connect to the Parse API"`

I noticed this error mentioned in https://github.com/OpenSignLabs/OpenSign/issues/559, as well.

**Comment by andrew-opensignlabs** [comment]
@prafull-opensignlabs can you please look into this?

**Comment by prafull-opensignlabs** [comment]
@wafflesrg00d  Thank you for pointing out this file. However, it is not used anywhere; it was mistakenly pushed by the developer and will be removed in an upcoming update.

**Comment by jsonpj3wt** [comment]
Hey @prafull-opensignlabs if that is not the code, then when is npx parse-dbtool migrate being called?  It is the hardcoded values too during docker compose just like thot line and will fail because it doesn't match the .env that is copied.

**Comment by prafull-opensignlabs** [comment]
hey @jsonpj3wt   Check the index.js file. There you will see the code for parse-dbtool migrate, where I have provided environment variables that get replaced at the time of execution. This is why you see actual values in the migration command, which might make it seem like there are hardcoded values.

**Comment by jsonpj3wt** [comment]
@prafull-opensignlabs ok great!  Thank you!

**Comment by jsonpj3wt** [comment]
I did have one more question on that, and I don't mind creating the merge request if needed, but since the .env does have the server URL, could we have it where that env var is used vs `http://localhost:8080/app`?  There may be a problem with that, since if you set it to `127.0.0.1:8080/app`, docker will likely not be too happy, but with that change we could change the port used, which is something that would cause us issues if we have other containers running and using that port.
